'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import type {Administrator} from '@/lib/contracts/admin-operations';
import {Field,Confirm,Section} from '@/features/admin-catalog/controls';
import {useOperation,useUnsaved} from './use-operation';
import {validateAuth} from '@/features/auth/validation';
import {validText} from './model';
export function AccountsEditor({items}:{items:Administrator[]}) {
 const op=useOperation(),router=useRouter(),[editing,setEditing]=useState<Administrator|null>(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[role,setRole]=useState<'OWNER'|'ADMIN'>('ADMIN'),[active,setActive]=useState(true),[review,setReview]=useState(false);
 const dirty=editing?name!==editing.name||email!==editing.email||role!==editing.role||active!==editing.active||!!password:!!name||!!email||!!password;useUnsaved(dirty);
 function clear(){setEditing(null);setName('');setEmail('');setPassword('');setConfirmation('');setRole('ADMIN');setActive(true);setReview(false);}
 function validate(){if(!validText(name,100,1))throw new Error('Ingresá un nombre de hasta 100 caracteres.');const result=validateAuth(!editing||password?'reset':'recovery',email,password,confirmation);if(Object.keys(result.errors).length)throw new Error(Object.values(result.errors).join(' '));return result.email;}
 async function save(){const normalizedEmail=validate();const changes=editing?Object.fromEntries(Object.entries({name:name.trim(),email:normalizedEmail,role,active}).filter(([key,value])=>value!==editing[key as keyof Administrator])):{name:name.trim(),email:normalizedEmail,role};const body={...changes,...(password?{password}:{})};if(!Object.keys(body).length){setReview(false);op.setMessage('No hay cambios para guardar.');return;}
 try{await op.manager.request('admin/admins'+(editing?'/'+editing.id:''),{method:editing?'PATCH':'POST',body});clear();op.setMessage('Administrador guardado.');router.refresh();await op.manager.refresh();}finally{setPassword('');setConfirmation('');setReview(false);}}
 return <><h1>Cuentas del panel</h1><p className="muted">Solo un propietario puede gestionar estas cuentas. Debe quedar al menos un propietario activo.</p>{op.message&&<p className="notice" role="alert">{op.message}</p>}
 <Section title={editing?'Editar cuenta':'Crear cuenta'}>{review?<div className="notice"><p>{editing?'Actualizar':'Crear'} la cuenta de <strong>{name}</strong> ({email}), rol {role==='OWNER'?'propietario':'administrador'}{editing?', '+(active?'activa':'inactiva'):''}.</p><p>Cambiar correo, contraseña, rol o desactivar la cuenta revoca sus sesiones. Si editás tu propia cuenta, puede cerrarse tu acceso.</p><div className="actions"><button className="button" disabled={op.disabled} onClick={()=>void op.run(save)}>Confirmar cuenta</button><button className="text-button" disabled={op.disabled} onClick={()=>setReview(false)}>Volver a editar</button></div></div>:<form method="post" onSubmit={e=>{e.preventDefault();try{validate();setReview(true);op.setMessage('');}catch(error){op.setMessage(error instanceof Error?error.message:'Revisá los datos.');}}}><fieldset className="editor-fields" disabled={op.disabled}><div className="editor-grid">
 <Field id="account-name" label="Nombre *" value={name} onChange={setName}/><Field id="account-email" label="Correo *" type="email" value={email} onChange={setEmail}/>
 <Field id="account-password" label={editing?'Nueva contraseña (opcional)':'Contraseña *'} type="password" value={password} onChange={setPassword} hint="Entre 12 y 128 caracteres. No se envía por correo automáticamente."/><Field id="account-confirmation" label="Repetir contraseña" type="password" value={confirmation} onChange={setConfirmation}/>
 <label className="custom-field">Rol<select id="account-role" value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="ADMIN">Administrador</option><option value="OWNER">Propietario</option></select></label></div>
 {editing&&<label className="check-label"><input id="account-active" type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Cuenta activa</label>}<div className="actions"><button className="button" type="submit">Revisar cuenta</button>{editing&&<Confirm label="Cancelar edición" question="¿Descartar esta edición?" onConfirm={clear}/>}</div></fieldset></form>}</Section>
 <div className="admin-product-list">{items.map(a=><article className="panel-card" key={a.id}><div><h2>{a.name}{a.id===op.session?.admin.id?' (tu cuenta)':''}</h2><p>{a.email}</p><p>{a.role==='OWNER'?'Propietario':'Administrador'} · {a.active?'Activo':'Inactivo'}</p></div><button className="text-button" disabled={op.disabled||review} onClick={()=>{if(dirty&&!window.confirm('¿Descartar los cambios actuales?'))return;setEditing(a);setName(a.name);setEmail(a.email);setPassword('');setConfirmation('');setRole(a.role);setActive(a.active);document.getElementById('account-name')?.focus();}}>Editar {a.name}</button></article>)}</div></>;
}
