'use client';
import Link from 'next/link';
import { useState } from 'react';
import type { AdminOrder,PaymentSummary,OrderStatus } from '@/lib/contracts/admin-operations';
import { Field,Confirm,Section } from '@/features/admin-catalog/controls';
import { useOperation } from './use-operation';
import { ORDER_LABELS,ORDER_NEXT,QUOTE_LABELS,money,date,timestamp,validText } from './model';
import { QuoteEditor } from './quote-editor';
import { PaymentEditor } from './payment-editor';
export function OrderDetail({initialOrder,initialPayments}:{initialOrder:AdminOrder;initialPayments:PaymentSummary}) {
 const op=useOperation(),[order,setOrder]=useState(initialOrder),[payments,setPayments]=useState(initialPayments);
 const [next,setNext]=useState<OrderStatus|''>(''),[reason,setReason]=useState('');
 async function refresh(){const [o,p]=await Promise.all([op.manager.request<AdminOrder>('admin/orders/'+order.id),op.manager.request<PaymentSummary>('admin/payments/orders/'+order.id)]);setOrder(o);setPayments(p);setNext('');setReason('');}
 return <><header className="editor-heading"><div><p className="eyebrow">Pedido {order.reference}</p><h1>{order.customerName}</h1><p>{ORDER_LABELS[order.status]}</p></div><Link className="text-link" href="/admin/pedidos">Volver a pedidos</Link></header>
 <button className="text-button" disabled={op.disabled} onClick={()=>void op.run(refresh)}>Actualizar pedido</button>{op.message&&<p className="notice" role="alert">{op.message}</p>}
 <Section title="Cliente y entrega"><dl className="operation-facts"><div><dt>Teléfono</dt><dd>{order.customerPhone}</dd></div><div><dt>Fecha solicitada</dt><dd>{date(order.requestedDate)}</dd></div><div><dt>Entrega</dt><dd>{order.deliveryMethod==='SHIPPING'?'Envío':'Retiro'}{order.deliveryAddress&&' · '+order.deliveryAddress}</dd></div><div><dt>Solicitado</dt><dd>{timestamp(order.createdAt)}</dd></div></dl>{order.notes&&<p className="plain-text">{order.notes}</p>}</Section>
 <Section title="Productos solicitados"><p className="muted">Estos datos corresponden al momento del pedido y se conservan aunque cambie el catálogo.</p>{order.items.map(item=><article className="collection-row" key={item.id}><h3>{item.productName} × {item.quantity}</h3><p>{item.variantSnapshot?.name??'Variante'} · {money(item.subtotalCents)}</p>{Object.entries(item.variantSnapshot?.attributes??{}).map(([key,value])=><p key={key}>{key}: {value}</p>)}{!!item.variantSnapshot?.photoCount&&<p>Fotos del cliente: {item.variantSnapshot.photoCount*item.quantity} (por WhatsApp).</p>}
 {(item.customizationSnapshot.answers??[]).map(answer=><p key={answer.fieldKey}><strong>{answer.label}</strong>{answer.componentKey&&' · '+(item.componentsSnapshot?.find(c=>c.key===answer.componentKey)?.name??'Componente')}: {String(answer.displayValue??answer.value)}</p>)}
 {(item.componentsSnapshot??[]).map(c=><p key={c.key}>Incluye {c.quantity} × {c.name}</p>)}</article>)}
 <p>Subtotal conocido: <strong>{money(order.knownSubtotalCents)}</strong></p><p>{order.pendingQuoteCount} productos pendientes de cotización · Envío: {money(order.shippingCents)}</p><p className="muted">El total acordado se define en el presupuesto aceptado.</p></Section>
 <Section title="Estado del pedido">{ORDER_NEXT[order.status].length?<fieldset disabled={op.disabled} className="editor-fields"><div className="editor-grid"><label className="custom-field">Nuevo estado<select id="order-status" value={next} onChange={e=>setNext(e.target.value as OrderStatus)}><option value="">Elegir</option>{ORDER_NEXT[order.status].map(s=><option key={s} value={s}>{ORDER_LABELS[s]}</option>)}</select></label><Field id="order-reason" label={next==='CANCELLED'?'Motivo de cancelación *':'Motivo (opcional)'} value={reason} onChange={setReason}/></div>
 <Confirm label="Cambiar estado" disabled={!next} question={'¿Pasar el pedido a '+(next?ORDER_LABELS[next]:'otro estado')+'?'} onConfirm={()=>op.run(async()=>{if(!next||!validText(reason,500,next==='CANCELLED'?1:0))throw new Error('Revisá el motivo: hasta 500 caracteres; obligatorio al cancelar.');await op.manager.request('admin/orders/'+order.id+'/status',{method:'PATCH',body:{status:next,reason:reason.trim()}});await refresh();op.setMessage('Estado actualizado.');})}/></fieldset>:<p>Este pedido está cerrado. Conserva su historial y admite devoluciones de saldo cobrado.</p>}</Section>
 <QuoteEditor order={order} refresh={refresh}/><PaymentEditor order={order} summary={payments} refresh={refresh}/>
 <Section title="Historial">{!order.events.length?<p>Sin eventos.</p>:<ol className="event-list">{order.events.map(e=><li key={e.id}><strong>{eventName(e.type)}</strong> · {timestamp(e.createdAt)}<EventDetails details={e.details}/></li>)}</ol>}</Section></>;
}
function eventName(type:string){return ({CREATED:'Pedido registrado',ORDER_CREATED:'Pedido registrado',STATUS_CHANGED:'Cambio de estado',QUOTE_CREATED:'Presupuesto creado',QUOTE_STATUS_CHANGED:'Estado de presupuesto',PAYMENT_RECORDED:'Movimiento registrado'} as Record<string,string>)[type]??'Evento del pedido';}
function EventDetails({details}:{details:Record<string,unknown>|null}) {if(!details)return null;const label=(value:unknown)=>typeof value==='string'?ORDER_LABELS[value as OrderStatus]??QUOTE_LABELS[value as keyof typeof QUOTE_LABELS]??value:'';return <>{details.from&&details.to?<p>{label(details.from)} → {label(details.to)}</p>:null}{typeof details.reason==='string'&&<p>{details.reason}</p>}{typeof details.version==='number'&&<p>Revisión {details.version}</p>}{typeof details.amountCents==='number'&&<p>{details.type==='REFUND'?'Devolución':'Cobro'}: {money(details.amountCents)}</p>}{typeof details.administratorId==='string'&&<details><summary>Identificación del administrador</summary><p>{details.administratorId}</p></details>}</>;}
