'use client';
import { useState } from 'react';
import type { AdminOrder,QuoteInput } from '@/lib/contracts/admin-operations';
import { Field,Section,Confirm } from '@/features/admin-catalog/controls';
import { ApiError } from '@/lib/api/errors';
import { buildQuote,money,QUOTE_LABELS,QUOTE_NEXT,timestamp,type QuoteDraft } from './model';
import { useOperation,useUnsaved } from './use-operation';
const empty:QuoteDraft={items:[],notes:''};
export function QuoteEditor({order,refresh}:{order:AdminOrder;refresh:()=>Promise<void>}) {
 const op=useOperation(),[draft,setDraft]=useState<QuoteDraft>(empty),[review,setReview]=useState<QuoteInput|null>(null),[uncertain,setUncertain]=useState(false);
 const closed=['CANCELLED','DELIVERED'].includes(order.status),latest=Math.max(0,...order.quotes.map(q=>q.version)),active=order.quotes.filter(q=>q.status==='ACCEPTED').sort((a,b)=>b.version-a.version)[0];
 useUnsaved(draft.items.length>0||!!draft.notes);
 const change=(i:number,patch:Partial<QuoteDraft['items'][number]>)=>setDraft({...draft,items:draft.items.map((x,n)=>n===i?{...x,...patch}:x)});
 return <Section title="Presupuestos"><p>Vigente: {active?'revisión '+active.version+' · '+money(active.totalCents):'todavía no hay un presupuesto aceptado'}. Una revisión nueva no reemplaza el acuerdo vigente hasta ser aceptada.</p>
 {op.message&&<p className="notice" role="alert">{op.message}</p>}
 {order.quotes.map(q=><article className="collection-row" key={q.id}><h3>Revisión {q.version} · {QUOTE_LABELS[q.status]}{q.id===active?.id?' · Vigente':''}</h3><p>{timestamp(q.createdAt)} · <strong>{money(q.totalCents)}</strong></p><ul>{q.items.map(item=><li key={item.id}>{item.productName} × {item.quantity} · {money(item.unitPriceCents)} por unidad · {money(item.subtotalCents)}{item.description&&<p>{item.description}</p>}</li>)}</ul>{q.notes&&<p className="plain-text">{q.notes}</p>}
 <div className="actions">{!closed&&QUOTE_NEXT[q.status].filter(s=>s!=='ACCEPTED'||q.version===latest).map(s=><Confirm key={s} label={s==='SENT'?'Registrar como enviado':s==='ACCEPTED'?'Registrar aceptación':'Registrar rechazo'} disabled={op.disabled}
 question={s==='SENT'?'¿Registrar que ya enviaste este presupuesto al cliente? Esta acción no envía mensajes.':s==='ACCEPTED'?'¿Registrar la aceptación acordada con el cliente por '+money(q.totalCents)+'?':'¿Registrar el rechazo de esta revisión?'}
 onConfirm={()=>op.run(async()=>{await op.manager.request('admin/orders/'+order.id+'/quotes/'+q.id+'/status',{method:'PATCH',body:{status:s}});await refresh();op.setMessage('Estado del presupuesto actualizado.');})}/>)}</div></article>)}
 {!closed&&<><h3>Nueva revisión</h3><p className="muted">Incluí todos los productos, adicionales y envío que formen el total final. Los importes pendientes deben completarse.</p>
 {uncertain?<div className="notice"><p>No se confirmó la creación. Actualizá el pedido y revisá las revisiones antes de crear otra.</p><button className="text-button" disabled={op.disabled} onClick={()=>void op.run(refresh)}>Consultar revisiones</button><Confirm label="Ya revisé las revisiones" question="¿Confirmás que revisaste el historial? Crear otra revisión podría duplicar un presupuesto si el anterior sí se guardó." disabled={op.disabled} onConfirm={()=>{setUncertain(false);setReview(null);}}/></div>:review?<div className="notice"><p>Total de la nueva revisión: <strong>{money(review.items.reduce((sum,i)=>sum+i.quantity*i.unitPriceCents,0))}</strong></p><div className="actions"><button className="button" disabled={op.disabled} onClick={()=>void op.run(async()=>{try{await op.manager.request('admin/orders/'+order.id+'/quotes',{method:'POST',body:review});}catch(e){if(!(e instanceof ApiError)||e.status>=500)setUncertain(true);throw e;}setDraft(empty);setReview(null);op.setMessage('Presupuesto creado.');await refresh();})}>Confirmar presupuesto</button><button className="text-button" disabled={op.disabled} onClick={()=>setReview(null)}>Volver a editar</button></div></div>:
 <form method="post" onSubmit={e=>{e.preventDefault();const result=buildQuote(draft);if(result.errors.length)op.setMessage(result.errors.join(' '));else{op.setMessage('');setReview(result.input);}}}><fieldset className="editor-fields" disabled={op.disabled}>
 <div className="actions"><Confirm label="Usar productos del pedido" question="¿Reemplazar el borrador con los productos originales? Completá manualmente los precios a cotizar y el envío." onConfirm={()=>setDraft({items:order.items.map(i=>({productName:i.productName,description:i.variantSnapshot?.name??'',quantity:String(i.quantity),price:i.unitPriceCents===null?'':(i.unitPriceCents/100).toFixed(2)})),notes:''})}/><button className="text-button" type="button" disabled={draft.items.length>=100} onClick={()=>setDraft({...draft,items:[...draft.items,{productName:'',description:'',quantity:'1',price:''}]})}>Agregar renglón</button></div>
 {draft.items.map((item,i)=><fieldset className="collection-row" key={i}><legend>Renglón {i+1}</legend><div className="editor-grid"><Field id={'quote-name-'+i} label="Concepto *" value={item.productName} onChange={productName=>change(i,{productName})}/><Field id={'quote-description-'+i} label="Descripción" value={item.description} onChange={description=>change(i,{description})}/><Field id={'quote-quantity-'+i} label="Cantidad *" value={item.quantity} onChange={quantity=>change(i,{quantity})}/><Field id={'quote-price-'+i} label="Precio unitario ARS *" value={item.price} onChange={price=>change(i,{price})}/></div><Confirm label="Quitar renglón" question="¿Quitar este renglón?" onConfirm={()=>setDraft({...draft,items:draft.items.filter((_,n)=>n!==i)})}/></fieldset>)}
 <Field id="quote-notes" label="Notas del presupuesto" value={draft.notes} onChange={notes=>setDraft({...draft,notes})} multiline/><button className="button" type="submit">Revisar presupuesto</button>
 </fieldset></form>}</>}
 </Section>;
}
